# Generated by Django 4.2.15 on 2024-08-14 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_temperature_data_temperature_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
